name 'tm-php'
maintainer 'The Authors'
maintainer_email 'taylor.monacelli@streambox.com'
license 'all_rights'
description 'Installs/Configures tm-php'
long_description 'Installs/Configures tm-php'
version '0.1.19'

depends 'ark', '>= 1.2.1'
depends 'vcruntime'
